FROM ros:humble-ros-base
LABEL authors="dadouuu"
WORKDIR /home

#### PROJECT SPECIFIQUE
ENV PROJECT=vision
#### END PROJECT SPECIFIQUE

EXPOSE 4421

RUN mkdir /home/ros2_ws
RUN mkdir /home/ros2_ws/src
RUN mkdir /home/ros2_ws/src/$PROJECT
RUN mkdir /home/ros2_ws/src/$PROJECT/resource

WORKDIR /home/ros2_ws/

COPY $PROJECT/ /home/ros2_ws/src/$PROJECT/$PROJECT/
COPY robot/ /home/ros2_ws/src/$PROJECT/robot/
COPY conf/ /home/ros2_ws/src/$PROJECT/conf/
COPY json/ /home/ros2_ws/src/$PROJECT/json/

#COPY dadou_utils_ros.tar.gz /home/ros2_ws/src/$PROJECT/
#RUN tar -xzhf /home/ros2_ws/src/$PROJECT/dadou_utils_ros.tar.gz -C /home/ros2_ws/src/$PROJECT/ && \
#    rm /home/ros2_ws/src/$PROJECT/dadou_utils_ros.tar.gz

COPY conf/ros2_dependencies/ /home/ros2_ws/src/

COPY conf/ros2/setup.py /home/ros2_ws/src/$PROJECT/
COPY conf/ros2/package.xml /home/ros2_ws/src/$PROJECT/
COPY conf/ros2/setup.cfg /home/ros2_ws/src/$PROJECT/
COPY conf/ros2/resource/ /home/ros2_ws/src/$PROJECT/resource/

RUN apt-get update && cat /home/ros2_ws/src/$PROJECT/conf/packages-docker.txt | xargs apt-get install -y

RUN ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

ENV PYTHONPATH "${PYTHONPATH}:/home/ros2_ws"

#### PROJECT SPECIFIQUE
RUN pip3 install -r /home/ros2_ws/src/$PROJECT/conf/requirements.txt
ENTRYPOINT ["/bin/bash", "-c", "source /home/scripts/launch-ros-in-docker.sh"]
#### FIN PROJECT SPECIFIQUE

#COPY robot/test.py .
#ENTRYPOINT ["python3", "test.py"]
#CMD ["python3", "src/run.py"]
