#disable main audio
#cd /etc/modprobe.d
#sudo vim alsa-blacklist.conf
#add blacklist snd_bcm2835
#add blacklist vc4

#remove hdmi audio
pcm.micro {
    type hw
    card 0
    device 0
}

pcm.speaker {
    type hw
    card 0
    device 0
}

pcm.!default {
    type hw
    card 0
    device 0
}

ctl.!default {
    type hw
    card 0
}

