#BUILD
#docker build -t nodes-helloworld .

# sudo apt-get install python3-dev python3-rpi.gpio




FROM ros:humble-ros-base
LABEL authors="dadouuu"
WORKDIR /home
# Copier le fichier requirements.txt dans le conteneur
#RUN apt-get update && apt-get install -y \
#    python3-pip \
#    libcairo2-dev \
#    pkg-config \
#    python3-dev


# Installer Python 3 et pip
#RUN apt-get update && apt-get install -y python3 python3-pip

EXPOSE 4421

#COPY packages.txt /home/packages.txt
#COPY requirements.txt /home/requirements.txt
RUN mkdir ros2_ws
COPY . /home/src/
#RUN git clone https://github.com/duvamduvam/DadouUtils.git
#RUN mv DadouUtils dadou_utils_ros

#RUN apt-get update && cat /tmp/packages.txt | xargs apt-get install -y
RUN apt-get update && apt-get install -y \
    ffmpeg \
    python3 \
    python3-pip \
    libcairo2-dev \
    pkg-config \
    python3-dev \
    libgirepository1.0-dev \
    libasound2-dev

ENV PYTHONPATH "${PYTHONPATH}:/home/src"
#RUN python3 -m venv /home/venv
#ENV PATH "/home/venv/bin:$PATH"

# Installer les bibliothèques Python à partir du fichier requirements.txt
RUN pip3 install -r /home/src/requirements.txt

RUN /bin/bash -c "source /opt/ros/humble/setup.bash"
#RUN cd src
#RUN /bin/bash -c "colcon build"

#COPY hello-nodes.py /home/
#CMD ["python3", "hello-nodes.py"]
CMD ["python3", "src/run.py"]
#ENTRYPOINT ["top", "-b"]